name       : libsavitar
version    : 4.7.1
release    : 12
source     :
    - https://github.com/Ultimaker/libSavitar/archive/4.7.1.tar.gz : 3287d155e20744bf09cfddb4dede72adb579c9dcc0a74e6f12ddde57f4d417b0
license    : LGPL-3.0-or-later
component  : programming.library
summary    : C++ implementation of 3mf loading with SIP python bindings
description: |
    Savitar is a C++ implementation of 3mf loading with SIP Python bindings.
    3mf is a 3D printing file format.
builddeps  :
    - pkgconfig(python3)
    - pugixml-devel
    - python3-sip-devel
setup      : |
    # Use system pugixml
    %patch -p1 < $pkgfiles/0001-Don-t-use-bundled-pugixml.patch

    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
